### ISSUE TITLE
Invalid ID causes game to crash instantly

### ISSUE THREAD

**Issue by ghost** [2mal3/2mal3s-Recipes#12]
Running on 1.19.4, editing the json files and removing the "2" from "2mal3s_recipes_mr" under ID fixes the problem.

### Error Log

```
---- Quilt Loader: Failed to load ----
Date/Time: 2023/04/07 21:43:16.6885

-- Error 1 --

Invalid 'quilt.mod.json' metadata file:<mods>/2mal3s-recipes-v1.7.1.jar!/quilt.mod.json

org.quiltmc.json5.exception.ParseException:  at line 1 column 66 path $.quilt_loader.id Invalid mod id, likely one of the following errors:
- Mod id contains invalid characters, the allowed characters are a-z 0-9 _-
- The mod id is too short or long, the mod id must be between 2 and 63 characters
	at org.quiltmc.loader.impl.metadata.qmj.ModMetadataReader.parseException(ModMetadataReader.java:114)
	at org.quiltmc.loader.impl.metadata.qmj.V1ModMetadataReader.readFields(V1ModMetadataReader.java:123)
	at org.quiltmc.loader.impl.metadata.qmj.V1ModMetadataReader.read(V1ModMetadataReader.java:70)
	at org.quiltmc.loader.impl.metadata.qmj.ModMetadataReader.read(ModMetadataReader.java:93)
	at org.quiltmc.loader.impl.metadata.qmj.ModMetadataReader.read(ModMetadataReader.java:47)
	at org.quiltmc.loader.impl.plugin.quilt.StandardQuiltPlugin.scan0(StandardQuiltPlugin.java:195)
	at org.quiltmc.loader.impl.plugin.quilt.StandardQuiltPlugin.scanZip(StandardQuiltPlugin.java:178)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanZip(QuiltPluginManagerImpl.java:1828)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFile0(QuiltPluginManagerImpl.java:1766)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFile(QuiltPluginManagerImpl.java:1716)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl$1.visitFile(QuiltPluginManagerImpl.java:1652)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl$1.visitFile(QuiltPluginManagerImpl.java:1548)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFolder0(QuiltPluginManagerImpl.java:1548)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFolder(QuiltPluginManagerImpl.java:1529)
	at org.quiltmc.loader.impl.plugin.MainThreadTask$ScanModFolderTask.execute(MainThreadTask.java:42)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runSingleCycle(QuiltPluginManagerImpl.java:1114)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runInternal(QuiltPluginManagerImpl.java:1057)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.run(QuiltPluginManagerImpl.java:515)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:484)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:271)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:263)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


-- Error 2 --

Invalid 'fabric.mod.json' metadata file:<mods>/2mal3s-recipes-v1.7.1.jar!/fabric.mod.json

org.quiltmc.loader.impl.fabric.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at unknown location: Invalid mod id 2mal3s_recipes_mr: It starts with an invalid character '2' (it must be a lowercase a-z - uppercase isn't allowed anywhere in the ID)
	at org.quiltmc.loader.impl.fabric.metadata.FabricModMetadataReader.checkModId(FabricModMetadataReader.java:253)
	at org.quiltmc.loader.impl.fabric.metadata.FabricModMetadataReader.parseMetadata(FabricModMetadataReader.java:68)
	at org.quiltmc.loader.impl.fabric.metadata.FabricModMetadataReader.parseMetadata(FabricModMetadataReader.java:60)
	at org.quiltmc.loader.impl.plugin.fabric.StandardFabricPlugin.scan0(StandardFabricPlugin.java:71)
	at org.quiltmc.loader.impl.plugin.fabric.StandardFabricPlugin.scanZip(StandardFabricPlugin.java:56)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanZip(QuiltPluginManagerImpl.java:1828)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFile0(QuiltPluginManagerImpl.java:1766)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFile(QuiltPluginManagerImpl.java:1716)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl$1.visitFile(QuiltPluginManagerImpl.java:1652)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl$1.visitFile(QuiltPluginManagerImpl.java:1548)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFolder0(QuiltPluginManagerImpl.java:1548)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFolder(QuiltPluginManagerImpl.java:1529)
	at org.quiltmc.loader.impl.plugin.MainThreadTask$ScanModFolderTask.execute(MainThreadTask.java:42)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runSingleCycle(QuiltPluginManagerImpl.java:1114)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runInternal(QuiltPluginManagerImpl.java:1057)
	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.run(QuiltPluginManagerImpl.java:515)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:484)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:271)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:263)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by 2mal3** [comment]
Thanks for reporting! Now fixed.
